### ISSUE TITLE
Help using the zip functions for 10-fold CV ZIP elastic net model with random hyperparameter search

### ISSUE THREAD

**Issue by delgaa07** [zhuwang46/mpath#6]
I'm trying to use your function for a 10-fold CV ZIP elastic net model with a hyperparameter optimization using random search. I am having trouble with executing this desired strategy and would like to see if my use of the function is correct - I feel I am only performing a LASSO, hence the name of the object. Attached is a portion of my script that is supposed to cover this part of my analysis. I have been able to run the model so far but my alpha values are still stuck at 1. Another question I have is regarding the image below, is the mixture parameter being selected for actually '1' or am I not programming the function correctly? 

![image](https://github.com/zhuwang46/mpath/assets/92696017/ecc252b5-342c-4953-9469-157030873011)

This image illustrates what's currently inside the object once run. 

Unfortunately, I am not allowed to share the data file b/c of HIPAA. However, I did provide a sample script with copy/pasted output from glimpse() of the de-identified dataframe. See the link below:

[Elastic Net ZIP mpath help.txt](https://github.com/zhuwang46/mpath/files/12303326/Elastic.Net.ZIP.mpath.help.txt)

Any help with this would be appreciated - thank you for creating this function!

**Comment by zhuwang46** [comment]
Please report any issues with respect to the package itself.
